name: EasyTP
version: '1.0'
main: pixelfox.easytp.EasyTP
api-version: '1.20'
commands:
  tpa:
    description: Request to teleport to another player.
    usage: /tpa <player>
  tpaccept:
    description: Accept a teleport request.
    usage: /tpaccept
  tpadeny:
    description: Deny a teleport request.
    usage: /tpadeny
  sethome:
    description: Set your home location.
    usage: /sethome <name>
  home:
    description: Teleport to your home location.
    usage: /home <name>
  delhome:
    description: Delete a home location.
    usage: /delhome <name>
  homes:
    description: List all your home locations.
    usage: /homes
    permission: easytp.homes
    permission-message: You do not have permission to use this command.
  homesview:
    description: View another player's home locations (admin only).
    usage: /homesview <player>
    permission: easytp.admin
    permission-message: You do not have permission to use this command.
  playerhometp:
    description: Teleport to a specified home of a player (admin only).
    usage: /playerhometp <player> <home>
    permission: easytp.admin
    permission-message: You do not have permission to use this command.
  back:
    description: Teleport to your last location.
    usage: /back
  tpr:
    description: Teleport to a random location.
    usage: /tpr
  death:
    description: Teleport to your last death location.
    usage: /death
permissions:
  easytp.admin:
    description: Allows access to admin commands.
    default: op
  easytp.homes:
    description: Allows access to the /homes command.
    default: true